### ISSUE TITLE
Output is mixed up if more than one command is run at the same time

### ISSUE THREAD

**Issue by davidemms** [hallamlab/LAST-Plus#5]
Hi

I'd really like to try out LAST-plus as it seems to be a lot quicker than BLAST. However, if I run more than one lastal+ command at the same time on my computer then the results from the separate processes (directed to different output files) get mixed up so that the output of one command ends up in the output file of a separate command. On my computer this can be reproduced by running `bash commands.sh` inside the directory in the attached tarball.
[io_error.tar.gz](https://github.com/hallamlab/LAST-Plus/files/354318/io_error.tar.gz)

The commands.sh looks like this:
`lastdb+ -p LastDBSpecies4 Species4.fa` 
`lastdb+ -p LastDBSpecies7 Species7.fa` 
`lastdb+ -p LastDBSpecies6 Species6.fa` 
`lastal+ -E 0.001 LastDBSpecies7 Species6.fa -K 100 -o Blast6_7.txt &`
`lastal+ -E 0.001 LastDBSpecies4 Species4.fa -K 100 -o Blast4_4.txt &`
`lastal+ -E 0.001 LastDBSpecies4 Species6.fa -K 100 -o Blast6_4.txt &`
`lastal+ -E 0.001 LastDBSpecies6 Species4.fa -K 100 -o Blast4_6.txt &`
`lastal+ -E 0.001 LastDBSpecies6 Species6.fa -K 100 -o Blast6_6.txt &`
`wait`

The script produces a set of results files of the form BlastX_Y.txt. If you look at the sequence names in the input files then you will see that, for example, Blast6_4.txt should only contain sequences called 6_... in the first column and sequences called 4_... in the second column. However, on my computer the file Blast6_4.txt produced by the command 
`lastal+ -E 0.001 LastDBSpecies4 Species6.fa -K 100 -o Blast6_4.txt` 
contains sequences from the file Species7.fa e.g. it contains the line 
`6_9998 7_4868  54  158 70  1   131 290 658 816 6.6258e-56  195`

I don't know if this problem occurs in a machine-dependent way so you may have to experiment to reproduce it or it may just work. Hope you're able to help!

All the best
David

**Comment by dongjaek** [comment]
Hi

LAST+ uses a tmp directory for external sorting which will conflict if multiple LAST+ processes are running on the same machine. It is advised to always use the maximum number of cores for a LAST+ run but in the case of multiple tenant (shared) computers multiple processes of LAST+ may be running. I intend to push a fix soon and will close this issue once I have pushed the fix.

Thank you for using LAST+

**Comment by davidemms** [comment]
Thanks! I'd like to allow people to use it when they run [OrthoFinder](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0721-2) as from the testing I've done I get a huge increase in speed with only a small drop in accuracy (77% vs 82% running OrthoFinder on a test set of orthogroups). And thanks for developing LAST+, it's a great tool and a really significant improvement in performance in an area where people have already focused a lot of attention!

**Comment by macmanes** [comment]
Any update on this? I manage a shared workstation and this bug worries me.

**Comment by kishori82** [comment]
The bug has been resolved, can you pull the new version and verify?

**Comment by davidemms** [comment]
Thanks. I've just downloaded the latest zip file from the master branch and I'm still getting the same problem unfortunately.

**Comment by dongjaek** [comment]
Please run the command like this:

lastdb+ -p LastDBSpecies4 Species4.fa 
lastdb+ -p LastDBSpecies7 Species7.fa 
lastdb+ -p LastDBSpecies6 Species6.fa 
lastal+ -E 0.001 -K 100 -o Blast6_7.txt LastDBSpecies7 Species6.fa &
lastal+ -E 0.001 -K 100 -o Blast4_4.txt LastDBSpecies4 Species4.fa &
lastal+ -E 0.001 -K 100 -o Blast6_4.txt LastDBSpecies4 Species6.fa &
lastal+ -E 0.001 -K 100 -o Blast4_6.txt LastDBSpecies6 Species4.fa &
lastal+ -E 0.001 -K 100 -o Blast6_6.txt LastDBSpecies6 Species6.fa &
wait

**Comment by davidemms** [comment]
Yes. The same problem still occurs.

**Comment by davidemms** [comment]
I've edited the code locally to print out the "potential_directory" variable in "externalsort.cc" and the output I got was:
`/tmpAOPZHb6U5krjv1F6eNfCH62IDsrgGDLASTtemp0
/tmpAOPZHb6U5krjv1F6eNfCH62IDsrgGDLASTtemp0
/tmpAOPZHb6U5krjv1F6eNfCH62IDsrgGDLASTtemp0
/tmpAOPZHb6U5krjv1F6eNfCH62IDsrgGDLASTtemp0
/tmpAOPZHb6U5krjv1F6eNfCH62IDsrgGDLASTtemp0`

i.e. the same temporary directory was created by each process. 

The 'time(NULL)' command you've used to seed the random number generator will return the current time in seconds, this is very likely to be the same as all the processes will start at almost exactly the same time.

Hope this helps
David

**Comment by kishori82** [comment]
Hey David,

Yes, you are probably right. Thanks for pointing it out. We will put in a
fix by picking the randomness, later today. For now, can you put a sleep
for a second or two before you start each instance.

Thanks,
Kishori

**Comment by davidemms** [comment]
Hi, I was thinking, given that it's me as a user that is running multiple processes perhaps I should be responsible for providing a random (unique, in fact) string to each separate process? As I'm a single process calling multiple instances this would be very easy for me to do whereas it's difficult for the individual processes to generate unique strings without communicating between themselves. Would you be able to provide an option on the command line for the user to provide their own unique string for the temporary directories?

**Comment by kishori82** [comment]
Hi,

Yes, it is a good idea. I will make the changes in the next two days.

Kishori

**Comment by davidemms** [comment]
Hi, have you had a chance to try out the changes? It'd be great to start using LAST-Plus!

Thanks
David
